
spring:
  application:
    name: suzume
  lifecycle:
    timeout-per-shutdown-phase: 60s
server:
  shutdown: graceful

info:
  application:
    name: Suzume


management:
  info:
    env:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env"